export const SYSTEM_ENDPOINTS = {
  health: "/health",
  ready: "/ready",
  openApi: "/openapi.json",
  docs: "/docs",
  docsTrailingSlash: "/docs/",
  docsCss: "/docs/swagger-ui.css",
  docsBundleJs: "/docs/swagger-ui-bundle.js",
} as const;

export const API_ENDPOINTS = {
  auth: {
    register: "/api/auth/register",
    login: "/api/auth/login",
    google: "/api/auth/google",
    verifySecondFactor: "/api/auth/verify-2fa",
    resendSecondFactor: "/api/auth/resend-2fa",
    refresh: "/api/auth/refresh",
    me: "/api/auth/me",
  },
  catalogos: {
    base: "/api/catalogos",
    roles: "/api/catalogos/roles",
    monedas: "/api/catalogos/monedas",
    impuestos: "/api/catalogos/impuestos",
    gruposArticulo: "/api/catalogos/grupos-articulo",
    almacenes: "/api/catalogos/almacenes",
    estadosDocumento: "/api/catalogos/estados-documento",
    tiposDocumento: "/api/catalogos/tipos-documento",
  },
  usuarios: "/api/usuarios",
  proveedores: "/api/proveedores",
  proveedoresById: "/api/proveedores/{id}",
  articulos: "/api/articulos",
  articulosById: "/api/articulos/{id}",
  ordenesCompra: "/api/ordenes-compra",
  ordenesCompraById: "/api/ordenes-compra/{id}",
  ordenesCompraApproveById: "/api/ordenes-compra/{id}/aprobar",
  ordenesCompraApproveSuffix: "/aprobar",
  ordenesCompraRecepcionesById: "/api/ordenes-compra/{id}/recepciones",
  ordenesCompraRecepcionesSuffix: "/recepciones",
  cuentasPorPagar: "/api/cuentas-por-pagar",
  cuentasPorPagarById: "/api/cuentas-por-pagar/{id}",
  cuentasPorPagarPagosById: "/api/cuentas-por-pagar/{id}/pagos",
  cuentasPorPagarPagosSuffix: "/pagos",
  pagosProveedor: "/api/pagos-proveedor",
  pagosProveedorById: "/api/pagos-proveedor/{id}",
  inventario: {
    stocks: "/api/inventario/stocks",
    movimientos: "/api/inventario/movimientos",
    movimientosById: "/api/inventario/movimientos/{id}",
  },
  auditoria: "/api/auditoria",
  auditoriaById: "/api/auditoria/{id}",
} as const;
