// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

declare module "*.css" {
  const css: string;
  export default css;
}

interface ImportMetaHotData {
  root?: import("react-dom/client").Root;
}

interface ImportMetaHot {
  data: ImportMetaHotData;
}

interface ImportMeta {
  hot?: ImportMetaHot;
}
